### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#383]
Below PRs need to be merged for a ADB release candidate build
- [x] https://github.com/projectatomic/adb-atomic-developer-bundle/pull/382

Tentative
- [x] https://github.com/projectatomic/adb-atomic-developer-bundle/pull/375
## Release candidate:

RC1: https://cbs.centos.org/koji/taskinfo?taskID=92890
Libvirt: http://cbs.centos.org/kojifiles/work/tasks/2891/92891/centos-7-adb-2.1-0.x86_64.rhevm.ova
Virtualbox: http://cbs.centos.org/kojifiles/work/tasks/2891/92891/centos-7-adb-2.1-0.x86_64.vsphere.ova

Things to test: 
- [x]  OpenShift Vagrantfile
- [x]  Kubernetes Vagrantfile
- [ ]  Mesos Marathon Vagrantfile
- [x]  vagrat-service-manager latest
- [x]  sccli commands

**Comment by dharmit** [comment]
For unkown reasons, on my CentOS 7 box, when I do vagrant up, I'm getting error like:

```
The provider 'libvirt' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
```

Necessary packages seem installed:

```
# rpm -qa  | grep vagrant | grep libvirt
sclo-vagrant1-vagrant-libvirt-0.0.32-1.el7.noarch
sclo-vagrant1-rubygem-fog-libvirt-0.0.1-6.el7.noarch
sclo-vagrant1-rubygem-ruby-libvirt-0.5.2-2.el7.x86_64
```

And libvirt's running as well

```
# systemctl status libvirtd
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2016-05-18 14:33:40 BST; 8min ago
     Docs: man:libvirtd(8)
           http://libvirt.org
 Main PID: 31888 (libvirtd)
   CGroup: /system.slice/libvirtd.service
           ├─13953 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─13954 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           └─31888 /usr/sbin/libvirtd

May 18 14:33:40 n49.dusty.ci.centos.org systemd[1]: Starting Virtualization daemon...
May 18 14:33:40 n49.dusty.ci.centos.org systemd[1]: Started Virtualization daemon.
May 18 14:33:40 n49.dusty.ci.centos.org dnsmasq[13953]: read /etc/hosts - 2 addresses
May 18 14:33:40 n49.dusty.ci.centos.org dnsmasq[13953]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 addresses
May 18 14:33:40 n49.dusty.ci.centos.org dnsmasq-dhcp[13953]: read /var/lib/libvirt/dnsmasq/default.hostsfile
```

I even tried restarting libvirtd

From a different system that's been working well since past few days, where I also observe the same issue:

```
# cat /var/log/yum.log | grep 'May 18'
May 18 06:11:42 Installed: httpd-tools-2.4.6-40.el7.centos.1.x86_64
May 18 06:11:42 Installed: mailcap-2.1.41-2.el7.noarch
May 18 06:11:45 Installed: httpd-2.4.6-40.el7.centos.1.x86_64
May 18 06:12:48 Installed: vsftpd-3.0.2-11.el7_2.x86_64
May 18 06:43:26 Installed: audit-libs-python-2.4.1-5.el7.x86_64
May 18 06:43:27 Installed: docker-forward-journald-1.9.1-25.el7.centos.x86_64
May 18 06:43:28 Installed: libsemanage-python-2.1.10-18.el7.x86_64
May 18 06:43:28 Installed: python-IPy-0.75-6.el7.noarch
May 18 06:43:28 Installed: checkpolicy-2.1.12-6.el7.x86_64
May 18 06:43:29 Installed: setools-libs-3.3.7-46.el7.x86_64
May 18 06:43:30 Installed: policycoreutils-python-2.2.5-20.el7.x86_64
May 18 06:43:42 Installed: docker-selinux-1.9.1-25.el7.centos.x86_64
May 18 06:43:45 Installed: docker-1.9.1-25.el7.centos.x86_64
May 18 07:03:17 Updated: sclo-vagrant1-runtime-2.1-3.el7.x86_64
May 18 07:03:18 Updated: sclo-vagrant1-2.1-3.el7.x86_64
May 18 07:03:20 Updated: sclo-vagrant1-vagrant-1.8.1-4.el7.noarch
May 18 07:03:20 Updated: libndp-1.2-6.el7_2.x86_64
```

**Comment by LalatenduMohanty** [comment]
@dharmit Can you please check your previous successful CI jobs to see what versions worked for you?

**Comment by brgnepal** [comment]
Kubernetes and Openshift looks fine.
Openshift new-app logs:

```
[[vagrant@centos7-adb ~]$ oc new-app nodejs-example
--> Deploying template nodejs-example in project openshift for "nodejs-example"
     With parameters:
      Memory Limit=512Mi
      Git Repository URL=https://github.com/openshift/nodejs-ex.git
      Git Reference=
      Context Directory=
      Application Hostname=
      GitHub Webhook Secret=GwXCt1UGcS1SadcyOfriG6lBFFRssFaqV0e4xW8S # generated
      Generic Webhook Secret=2k2ignqe3HoauAVySlAbN2YFNgIqAmWokHDA1X7L # generated
      Database Service Name=
      MongoDB Username=
      MongoDB Password=
      Database Name=
      Database Administrator Password=
--> Creating resources with label app=nodejs-example ...
    Service "nodejs-example" created
    Route "nodejs-example" created
    ImageStream "nodejs-example" created
    BuildConfig "nodejs-example" created
    DeploymentConfig "nodejs-example" created
--> Success
    Build scheduled for "nodejs-example" - use the logs command to track its progress.
    Run 'oc status' to view your app.

[vagrant@centos7-adb ~]$ oc status
In project OpenShift sample project (sample-project) on server https://127.0.0.1:8443
svc/nodejs-example - 172.30.250.112:8080
  dc/nodejs-example deploys imagestreamtag/nodejs-example:latest <-
    bc/nodejs-example builds https://github.com/openshift/nodejs-ex.git with openshift/nodejs:0.10 
      #1 build running for 4 seconds
    #1 deployment waiting on image or update
  exposed by route/nodejs-example
1 warning identified, use 'oc status -v' to see details.

###### sccli 

[vagrant@centos7-adb ~]$ sccli
usage: sccli [-h] {kubernetes,openshift,docker} ...
sccli: error: too few arguments

[vagrant@centos7-adb ~]$ sudo sccli kubernetes start
[vagrant@centos7-adb ~]$ sudo kubectl get nodes
NAME        LABELS                             STATUS    AGE
127.0.0.1   kubernetes.io/hostname=127.0.0.1   Ready     54s

```

**Comment by praveenkumar** [comment]
@LalatenduMohanty Openshift tested using latest VSM and also tested `sccli` interaction with kubernetes.

```
]$ oc new-app nodejs-example
--> Deploying template nodejs-example in project openshift for "nodejs-example"
     With parameters:
      Memory Limit=512Mi
      Git Repository URL=https://github.com/openshift/nodejs-ex.git
      Git Reference=
      Context Directory=
      Application Hostname=
      GitHub Webhook Secret=XfSWbguFjvXwP1VhFxu8HT8rJ5qBE66l2YcV32GX # generated
      Generic Webhook Secret=7ayleuYfITyjiYw1VlUpJGpjxV4WLq4N6hDs3UiD # generated
      Database Service Name=
      MongoDB Username=
      MongoDB Password=
      Database Name=
      Database Administrator Password=
--> Creating resources with label app=nodejs-example ...
    Service "nodejs-example" created
    Route "nodejs-example" created
    ImageStream "nodejs-example" created
    BuildConfig "nodejs-example" created
    DeploymentConfig "nodejs-example" created
--> Success
    Build scheduled for "nodejs-example" - use the logs command to track its progress.
    Run 'oc status' to view your app.
[vagrant@centos7-adb ~]$ oc status
In project OpenShift sample project (sample-project) on server https://10.1.2.7:8443

svc/nodejs-example - 172.30.87.157:8080
  dc/nodejs-example deploys imagestreamtag/nodejs-example:latest <-
    bc/nodejs-example builds https://github.com/openshift/nodejs-ex.git with openshift/nodejs:0.10 
    #1 deployed 3 minutes ago - 1 pod
  exposed by route/nodejs-example

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
[vagrant@centos7-adb ~]$ sccli -h
usage: sccli [-h] {kubernetes,openshift,docker} ...

CLI for managing services in ADB/CDK

optional arguments:
  -h, --help            show this help message and exit

subcommands:
  Manage services for openshift|docker|kubernetes

  {kubernetes,openshift,docker}
    kubernetes          start|restart|status|stop (default:start)
    openshift           start|restart|status|stop (default:start)
    docker              start|restart|status|stop (default:start)
[vagrant@centos7-adb ~]$ sccli kubernetes start
Execution Permision Denied (use sudo)
[vagrant@centos7-adb ~]$ sudo !!
sudo sccli kubernetes start
[vagrant@centos7-adb ~]$ kubectl get nodes
NAME        LABELS                             STATUS    AGE
127.0.0.1   kubernetes.io/hostname=127.0.0.1   Ready     5s
```

**Comment by brgnepal** [comment]
While testing ADB2.1 rc build in context of `Mesos` vagrantfile, I am getting following error on running atomic app:

```
[vagrant@centos7-adb ~]$ sudo -E atomic run projectatomic/helloapache
Using default tag: latest
Trying to pull repository docker.io/projectatomic/helloapache ... latest: Pulling from projectatomic/helloapache

1544084fad81: Pull complete 
ddca430e683e: Pull complete 
bb35b9816560: Pull complete 
000ef0017d51: Pull complete 
791aa4db7bf5: Pull complete 
e22ce82dd916: Pull complete 
ce5186eb3178: Pull complete 
b23c610a38f3: Pull complete 
f6d800e24ad6: Pull complete 
b65118b7bf8d: Pull complete 
cd29e94d221e: Pull complete 
3b21d33b38dc: Pull complete 
571bc8a9a251: Pull complete 
1ad98c959a62: Pull complete 
3dc677cf4210: Pull complete 
3babe300827e: Pull complete 
391a5d2f7624: Pull complete 
f586e68f16ce: Pull complete 
ef583edee5df: Pull complete 
Digest: sha256:02adee50f60ba50626afa9e697edfe81137d1b82d2f22eccfed225736f96c7ab
Status: Downloaded newer image for docker.io/projectatomic/helloapache:latest

docker run -it --rm --privileged -v /home/vagrant:/atomicapp -v /run:/run -v /:/host --net=host --name helloapache -e USER -e SUDO_USER -e NAME=helloapache -e IMAGE=projectatomic/helloapache projectatomic/helloapache run

This container uses privileged security switches:

INFO: --net=host 
      Processes in this container can listen to ports (and possibly rawip traffic) on the host's network.

INFO: --privileged 
      This container runs without separation and should be considered the same as root on your system.

For more information on these switches and their security implications, consult the manpage for 'docker run'.

[INFO] - main.py - Action/Mode Selected is: run
[INFO] - base.py - Unpacking image: projectatomic/helloapache to /host/var/lib/atomicapp/projectatomic-helloapache-58c749864e7f
[INFO] - container.py - Skipping pulling Docker image: projectatomic/helloapache
[INFO] - container.py - Extracting nulecule data from image: projectatomic/helloapache to /host/var/lib/atomicapp/projectatomic-helloapache-58c749864e7f
b9a8c2a296c18b07839315bcdcbb5e4fe073e9143a8a723693deddbe9d2a347b
[WARNING] - plugin.py - Configuration option 'provider-config' not found
[WARNING] - plugin.py - Configuration option 'provider-config' not found
[INFO] - kubernetes.py - Using namespace default
[INFO] - kubernetes.py - trying kubectl at /host/usr/bin/kubectl
[INFO] - kubernetes.py - found kubectl at /host/usr/bin/kubectl
[INFO] - kubernetes.py - Deploying to Kubernetes
[ERROR] - main.py - cmd: ['/host/usr/bin/kubectl', 'create', '-f', u'/host/var/lib/atomicapp/projectatomic-helloapache-58c749864e7f/artifacts/kubernetes/.hello-apache-pod.json', '--namespace=default'] failed: 
Error from server: the server could not find the requested resource
Traceback (most recent call last):
  File "/opt/atomicapp/atomicapp/cli/main.py", line 130, in cli_func_exec
    cli_func(cli_func_args)
  File "/opt/atomicapp/atomicapp/cli/main.py", line 84, in cli_run
    nm.run(**argdict)
  File "/opt/atomicapp/atomicapp/nulecule/main.py", line 322, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/opt/atomicapp/atomicapp/nulecule/base.py", line 205, in run
    component.run(provider_key, dryrun)
  File "/opt/atomicapp/atomicapp/nulecule/base.py", line 340, in run
    provider.run()
  File "/opt/atomicapp/atomicapp/providers/kubernetes.py", line 189, in run
    self._call(cmd)
  File "/opt/atomicapp/atomicapp/providers/kubernetes.py", line 114, in _call
    ec, stdout, stderr = Utils.run_cmd(cmd, checkexitcode=True)
  File "/opt/atomicapp/atomicapp/utils.py", line 266, in run_cmd
    "cmd: %s failed: \n%s" % (str(cmd), stderr))
AtomicAppUtilsException: cmd: ['/host/usr/bin/kubectl', 'create', '-f', u'/host/var/lib/atomicapp/projectatomic-helloapache-58c749864e7f/artifacts/kubernetes/.hello-apache-pod.json', '--namespace=default'] failed: 
Error from server: the server could not find the requested resource

```

**Comment by brgnepal** [comment]
After dharmit's suggestion to [setup `atomicapp`](https://github.com/projectatomic/atomicapp#installing-atomic-app), command 

```
sudo -E atomicapp run --provider=marathon projectatomic/helloapache
```

 works fine and following command

```
curl localhost:8080/v2/apps/helloapache | python -m json.tool
```

give expected output.

**Comment by brgnepal** [comment]
Completed testing of `vagrant service-manager latest(1.0.2)`.

```
➜  centos-openshift-setup git:(master) ✗ vagrant service-manager env
# docker env:
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://10.1.2.2:2376
export DOCKER_CERT_PATH=/home/budhram/redhat/adb-atomic-developer-bundle/components/centos/centos-openshift-setup/.vagrant/machines/default/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.21

# openshift env:
# You can access the OpenShift console on: https://10.1.2.2:8443/console
# To use OpenShift CLI, run: oc login https://10.1.2.2:8443
export OPENSHIFT_URL=https://10.1.2.2:8443
export OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console

# run following command to configure your shell:
# eval "$(vagrant service-manager env)"
➜  centos-openshift-setup git:(master) ✗ vagrant service-manager env --script-readable
DOCKER_HOST=tcp://10.1.2.2:2376
DOCKER_CERT_PATH='/home/budhram/redhat/adb-atomic-developer-bundle/components/centos/centos-openshift-setup/.vagrant/machines/default/virtualbox/docker'
DOCKER_TLS_VERIFY=1
DOCKER_API_VERSION=1.21
OPENSHIFT_URL=https://10.1.2.2:8443
OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console

➜  centos-openshift-setup git:(master) ✗ vagrant service-manager box version --script-readable
VARIANT="Atomic Developer Bundle (ADB)"
VARIANT_ID="adb"
VARIANT_VERSION="2.1.0"

➜  centos-openshift-setup git:(master) ✗ vagrant service-manager status                       
Configured services:
docker - running
openshift - running
kubernetes - stopped

➜  centos-openshift-setup git:(master) ✗ vagrant service-manager restart docker

➜  centos-openshift-setup git:(master) ✗ vagrant ssh -c "sudo systemctl status docker"
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/docker.service.d
           └─flannel.conf
   Active: active (running) since Thu 2016-05-19 08:24:30 EDT; 10s ago
     Docs: http://docs.docker.com
..................
```

**Comment by brgnepal** [comment]
LGTM.

**Comment by praveenkumar** [comment]
Release is done and announced publicly: https://www.redhat.com/archives/container-tools/2016-May/msg00077.html (closing this issue now).
