### ISSUE TITLE
ADB does not start on Fedora 23 with RVM installed

### ISSUE THREAD

**Issue by ALRubinger** [projectatomic/adb-atomic-developer-bundle#393]
To reproduce:

1) Use base installation of Fedora 23 Workstation
2) Follow [installation instructions for ADB](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/installing.rst)
3) `vagrant up` on `components/centos/centos-openshift-setup`
4) Observe all is good in the world
5) Install RVM with Ruby: `\curl -sSL https://get.rvm.io | bash -s stable --ruby` as detailed by [these instructions](https://rvm.io/rvm/install)
6) Log out and log in again to ensure fresh environment as sourced from dotfiles (ie. ~/.bash_profile and friends)
7) Attempt to perform step 3 again
8) Observe:

```
$ which ruby
~/.rvm/rubies/ruby-2.3.0/bin/ruby
$ vagrant up
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring ruby-libvirt-0.6.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.6.0
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring ruby-libvirt-0.6.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.6.0
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
/usr/share/gems/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
    from /usr/share/gems/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:29:in `rescue in <top (required)>'
    from /usr/share/gems/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:25:in `<top (required)>'
    from /home/alr/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml.rb:2:in `require'
    from /home/alr/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml.rb:2:in `<top (required)>'
    from /usr/share/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt.rb:2:in `require'
    from /usr/share/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt.rb:2:in `<top (required)>'
    from /home/alr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/driver.rb:1:in `require'
    from /home/alr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/driver.rb:1:in `<top (required)>'
    from /home/alr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/provider.rb:29:in `require'
    from /home/alr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/provider.rb:29:in `driver'
    from /home/alr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/provider.rb:101:in `state'
    from /usr/share/vagrant/lib/vagrant/machine.rb:501:in `state'
    from /usr/share/vagrant/lib/vagrant/machine.rb:144:in `initialize'
    from /usr/share/vagrant/lib/vagrant/vagrantfile.rb:79:in `new'
    from /usr/share/vagrant/lib/vagrant/vagrantfile.rb:79:in `machine'
    from /usr/share/vagrant/lib/vagrant/environment.rb:663:in `machine'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:183:in `each'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
    from /usr/share/vagrant/plugins/commands/up/command.rb:89:in `block in execute'
    from /usr/share/vagrant/lib/vagrant/environment.rb:278:in `block (2 levels) in batch'
    from /usr/share/vagrant/lib/vagrant/environment.rb:276:in `tap'
    from /usr/share/vagrant/lib/vagrant/environment.rb:276:in `block in batch'
    from /usr/share/vagrant/lib/vagrant/environment.rb:275:in `synchronize'
    from /usr/share/vagrant/lib/vagrant/environment.rb:275:in `batch'
    from /usr/share/vagrant/plugins/commands/up/command.rb:88:in `execute'
    from /usr/share/vagrant/lib/vagrant/cli.rb:42:in `execute'
    from /usr/share/vagrant/lib/vagrant/environment.rb:302:in `cli'
    from /usr/share/vagrant/bin/vagrant:174:in `<main>'
```

9) OK, so let's try to fix this by installing the `nokogiri` gem.

```
$ which gem
~/.rvm/rubies/ruby-2.3.0/bin/gem
$ gem install nokogiri
Fetching: mini_portile2-2.0.0.gem (100%)
Successfully installed mini_portile2-2.0.0
Fetching: nokogiri-1.6.7.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.7.2
Parsing documentation for mini_portile2-2.0.0
Installing ri documentation for mini_portile2-2.0.0
Parsing documentation for nokogiri-1.6.7.2
Installing ri documentation for nokogiri-1.6.7.2
Done installing documentation for mini_portile2, nokogiri after 3 seconds
2 gems installed
```

10) Cool, let's try `vagrant up` again:

```
$ vagrant up
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring ruby-libvirt-0.6.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.6.0
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring ruby-libvirt-0.6.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.6.0
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
/usr/share/gems/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
    from /usr/share/gems/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:29:in `rescue in <top (required)>'
    from /usr/share/gems/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:25:in `<top (required)>'
    from /home/alr/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml.rb:2:in `require'
    from /home/alr/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml.rb:2:in `<top (required)>'
    from /usr/share/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt.rb:2:in `require'
    from /usr/share/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt.rb:2:in `<top (required)>'
    from /home/alr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/driver.rb:1:in `require'
    from /home/alr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/driver.rb:1:in `<top (required)>'
    from /home/alr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/provider.rb:29:in `require'
    from /home/alr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/provider.rb:29:in `driver'
    from /home/alr/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/provider.rb:101:in `state'
    from /usr/share/vagrant/lib/vagrant/machine.rb:501:in `state'
    from /usr/share/vagrant/lib/vagrant/machine.rb:144:in `initialize'
    from /usr/share/vagrant/lib/vagrant/vagrantfile.rb:79:in `new'
    from /usr/share/vagrant/lib/vagrant/vagrantfile.rb:79:in `machine'
    from /usr/share/vagrant/lib/vagrant/environment.rb:663:in `machine'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:183:in `each'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
    from /usr/share/vagrant/plugins/commands/up/command.rb:89:in `block in execute'
    from /usr/share/vagrant/lib/vagrant/environment.rb:278:in `block (2 levels) in batch'
    from /usr/share/vagrant/lib/vagrant/environment.rb:276:in `tap'
    from /usr/share/vagrant/lib/vagrant/environment.rb:276:in `block in batch'
    from /usr/share/vagrant/lib/vagrant/environment.rb:275:in `synchronize'
    from /usr/share/vagrant/lib/vagrant/environment.rb:275:in `batch'
    from /usr/share/vagrant/plugins/commands/up/command.rb:88:in `execute'
    from /usr/share/vagrant/lib/vagrant/cli.rb:42:in `execute'
    from /usr/share/vagrant/lib/vagrant/environment.rb:302:in `cli'
    from /usr/share/vagrant/bin/vagrant:174:in `<main>'
```

11) Screw, it, let's kill RVM and try to see if we can boot ADB after that:

```
$ which rvm
~/.rvm/bin/rvm
$ rvm implode
Are you SURE you wish for rvm to implode?
This will recursively remove /home/alr/.rvm and other rvm traces?
(anything other than 'yes' will cancel) > yes
Removing rvm-shipped binaries (rvm-prompt, rvm, rvm-sudo rvm-shell and rvm-auto-ruby)
Removing rvm wrappers in /home/alr/.rvm/bin
Hai! Removing /home/alr/.rvm
/home/alr/.rvm has been removed.

Note you may need to manually remove /etc/rvmrc and ~/.rvmrc if they exist still.
Please check all .bashrc .bash_profile .profile and .zshrc for RVM source lines and delete or comment out if this was a Per-User installation.
Also make sure to remove `rvm` group if this was a system installation.
Finally it might help to relogin / restart if you want to have fresh environment (like for installing RVM again).

$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
==> default: Creating shared folders metadata...
==> default: Copying TLS certificates to /home/alr/vagrant/adb/adb-atomic-developer-bundle/components/centos/centos-openshift-setup/.vagrant/machines/default/libvirt/docker
==> default: Rsyncing folder: /home/alr/vagrant/adb/adb-atomic-developer-bundle/components/centos/centos-openshift-setup/ => /vagrant
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
```

12) It works again.

**Comment by hferentschik** [comment]
Where is Vagrant coming from? Installed via yum?

**Comment by ALRubinger** [comment]
@hferentschik Yeah "dnf install vagrant-libvirt"

**Comment by ncoghlan** [comment]
I ran into some very similar error messages in Fedora 24, and they seemed to be due to cached gems in `~/.gems` and `~/.vagrant.d`.
