### ISSUE TITLE
Use PROXY* as variable instead of constant

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/adb-atomic-developer-bundle#606]
`PROXY*` entities are declared as constant in Vagrantfile but used as variable like [here](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/rhel-ose/Vagrantfile#L69-L71).

This will have side effect when exporting these entities via terminal as constants in Ruby as global.

```
/home/budhram/redhat/vagrant-service-manager/Vagrantfile:69: warning: already initialized constant PROXY
/home/budhram/redhat/vagrant-service-manager/Vagrantfile:69: warning: previous definition of PROXY was here
/home/budhram/redhat/vagrant-service-manager/Vagrantfile:94:in `block in <top (required)>': uninitialized constant PROXY_USER (NameError)
	from /home/budhram/.rvm/gems/ruby-2.1.2/bundler/gems/vagrant-bedaeee190b2/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /home/budhram/.rvm/gems/ruby-2.1.2/bundler/gems/vagrant-bedaeee190b2/lib/vagrant/config/v2/loader.rb:37:in `load'
........
```

**Comment by brgnepal** [comment]
Related to https://issues.jboss.org/browse/CDK-37.
